# Generated by Django 5.1.15 on 2026-07-17 15:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("furniture", "Furniture"),
                            ("electronics", "Electronics"),
                            ("stationery", "Stationery"),
                            ("sports", "Sports"),
                            ("library", "Library"),
                            ("lab_equipment", "Lab Equipment"),
                            ("cleaning", "Cleaning"),
                            ("medical", "Medical"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("unit_of_measurement", models.CharField(blank=True, max_length=32)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("invoice_po_number", models.CharField(blank=True, max_length=64)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="inventory/")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="inventory_i_search__1f1b3e_gin"
                    )
                ],
            },
        ),
    ]
