# Generated by Django 5.1.15 on 2026-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="date_acquired",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="min_stock_alert",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="storage_location",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
