# Generated by Django 5.1.15 on 2026-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
