# Generated by Django 5.1.15 on 2026-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("charter", "Charter"),
                            ("international", "International"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                ("established_year", models.PositiveIntegerField(blank=True, null=True)),
                ("affiliation_board", models.CharField(blank=True, max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="branding/")),
                ("primary_color", models.CharField(default="#6366F1", max_length=7)),
                ("invoice_prefix", models.CharField(default="INV", max_length=16)),
                ("invoice_footer_note", models.TextField(blank=True)),
                (
                    "default_late_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("notify_due_reminders", models.BooleanField(default=True)),
                ("notify_overdue", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "School settings",
                "verbose_name_plural": "School settings",
            },
        ),
    ]
