# Generated by Django 5.1.15 on 2026-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolsettings",
            name="address",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="default_late_fee_percent",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="email",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="primary_color",
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="accounts_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="bank_account_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="brand_color",
            field=models.CharField(default="#4F46E5", max_length=7),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="default_tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="facebook",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="instagram",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="letterhead_logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="official_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="payment_due_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="primary_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="starting_invoice_number",
            field=models.PositiveIntegerField(default=1001),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="tax_gst_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
