# Generated by Django 5.1.15 on 2026-07-19 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_remove_schoolsettings_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="payroll_esi_rate",
            field=models.DecimalField(decimal_places=4, default=Decimal("0.0075"), max_digits=6),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="payroll_esi_threshold",
            field=models.DecimalField(decimal_places=2, default=Decimal("21000"), max_digits=12),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="payroll_pf_ceiling",
            field=models.DecimalField(decimal_places=2, default=Decimal("15000"), max_digits=12),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="payroll_pf_rate",
            field=models.DecimalField(decimal_places=4, default=Decimal("0.12"), max_digits=6),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="payroll_professional_tax",
            field=models.DecimalField(decimal_places=2, default=Decimal("200"), max_digits=12),
        ),
    ]
