# Generated by Django 5.1.15 on 2026-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UdiseSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state_id", models.CharField(blank=True, max_length=20)),
                ("state_name", models.CharField(blank=True, max_length=200)),
                ("district_name", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("class_to", models.CharField(blank=True, max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("school_name", models.CharField(max_length=300)),
                ("mail_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "UDISE school",
                "verbose_name_plural": "UDISE schools",
                "ordering": ("school_name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school_name", "address", "state_id"), name="uniq_udise_school"
                    )
                ],
            },
        ),
    ]
