# Generated by Django 5.1.15 on 2026-07-21 12:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("warden_name", models.CharField(blank=True, max_length=120)),
                ("warden_phone", models.CharField(blank=True, max_length=32)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="HostelExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mess", "Mess / Food"),
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("staff_salary", "Staff Salary"),
                            ("other", "Other"),
                        ],
                        default="mess",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("spent_on", models.DateField(db_index=True)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("payment_method", models.CharField(blank=True, max_length=32)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ("-spent_on", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_number", models.CharField(max_length=20)),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ("hostel", "room_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hostel", "room_number"), name="uniq_hostel_room"
                    )
                ],
            },
        ),
    ]
