# Generated by Django 5.1.15 on 2026-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0002_alter_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("paypal", "PayPal"),
                    ("upi", "UPI"),
                    ("cheque", "Cheque"),
                    ("razorpay", "Razorpay"),
                ],
                max_length=16,
            ),
        ),
    ]
