# Generated by Django 5.1.15 on 2026-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0008_signingkey_payment_signature_payment_signed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
