# Generated by Django 5.1.15 on 2026-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0009_alter_creditnote_currency_alter_invoice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
