# Generated by Django 5.1.15 on 2026-07-17 22:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="full_name",
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacher",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("visiting", "Visiting"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="teacher",
            name="increment_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="teacher",
            name="increment_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="teacher",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_increment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="next_increment_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="pay_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("biweekly", "Bi-weekly"),
                    ("weekly", "Weekly"),
                    ("annual", "Annual"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="teachers/"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="qualification",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("on_leave", "On Leave"),
                    ("available", "Available"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TeacherClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("class_name", models.CharField(max_length=100)),
                ("role_in_class", models.CharField(blank=True, max_length=60)),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="staff.teacher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
