# Generated by Django 5.1.15 on 2026-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_remove_teacher_full_name_teacher_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
