# Generated by Django 5.1.15 on 2026-07-21 06:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_alter_payout_currency_alter_teacher_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="increment_percent",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="increment_reason",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="last_increment_date",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="next_increment_due",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="routing_code",
        ),
        migrations.AddField(
            model_name="payout",
            name="days_absent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="days_present",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="deduction_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payout",
            name="level",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="teacher",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="teacher",
            name="branch",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="teacher",
            name="hra",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="teacher",
            name="medical_allowance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="other_allowance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="other_deduction",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="pf_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="teacher",
            name="tds_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
