# Generated by Django 5.1.15 on 2026-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_remove_teacher_increment_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payout",
            name="level",
        ),
        migrations.AddField(
            model_name="payout",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="payout",
            name="deduction_reason",
            field=models.TextField(blank=True),
        ),
    ]
