# Generated by Django 5.1.15 on 2026-07-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_label", models.CharField(blank=True, max_length=200)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("entity_type", models.CharField(blank=True, max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="core_auditl_entity__244637_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="core_auditl_action_29a2bf_idx"
                    ),
                ],
            },
        ),
    ]
