# Generated by Django 5.1.15 on 2026-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title if left blank.",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Short summary shown on the blog list.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Post content. Separate paragraphs with a blank line."
                    ),
                ),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Only published posts appear on the site."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Set automatically when first published.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Optional grouping, e.g. 'Billing'.", max_length=80
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Lower numbers show first."),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ("order", "id"),
            },
        ),
    ]
