# Generated by Django 5.1.15 on 2026-07-17 15:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salaries", "Salaries"),
                            ("utilities", "Utilities"),
                            ("maintenance", "Maintenance"),
                            ("supplies", "Supplies"),
                            ("transport", "Transport"),
                            ("events", "Events"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expense_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=32)),
                ("reimbursable", models.BooleanField(default=False)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("project_cost_center", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("receipt", models.FileField(blank=True, null=True, upload_to="expenses/")),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-expense_date",),
            },
        ),
    ]
