# Generated by Django 5.1.15 on 2026-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
