# Generated by Django 5.1.15 on 2026-07-17 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("occurred_on", models.DateField(db_index=True)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-occurred_on", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["entry_type", "occurred_on"], name="finance_led_entry_t_c0b404_idx"
                    )
                ],
            },
        ),
    ]
