# Generated by Django 5.1.15 on 2026-07-18 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_student_enrollment_date_student_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_label", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access", "Access / export"),
                            ("erasure", "Erasure"),
                            ("rectification", "Rectification"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("data_processing", "Core data processing"),
                            ("marketing", "Marketing / newsletters"),
                            ("photo_usage", "Photo & media usage"),
                            ("third_party", "Third-party sharing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("enrolment", "Enrolment form"),
                            ("portal", "Parent portal"),
                            ("import", "Bulk import"),
                            ("staff", "Recorded by staff"),
                        ],
                        default="staff",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "purpose"), name="uniq_consent_student_purpose"
                    )
                ],
            },
        ),
    ]
