# Generated by Django 5.1.15 on 2026-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="code",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="client",
            name="slug",
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
