# Generated by Django 5.1.15 on 2026-07-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_client_code_client_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("table_count_total", models.BigIntegerField(default=0)),
                ("table_counts", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
