# Generated by Django 5.1.15 on 2026-07-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_client_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("max_students", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("price_monthly",),
            },
        ),
        migrations.AddField(
            model_name="client",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="tenants.plan",
            ),
        ),
    ]
