# Generated by Django 5.1.15 on 2026-07-22 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_plan_code_plan_description_plan_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backups",
                to="tenants.client",
            ),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="schema_name",
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="storage_key",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
