# Generated by Django 5.1.15 on 2026-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_backuprun_client_backuprun_schema_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSupportCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=16, unique=True)),
                ("schema_name", models.CharField(db_index=True, max_length=63)),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("school_code", models.CharField(blank=True, max_length=32)),
                ("user_name", models.CharField(blank=True, max_length=200)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_phone", models.CharField(blank=True, max_length=32)),
                ("topic", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("verified", "Verified"),
                            ("closed", "Closed"),
                        ],
                        default="issued",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "WhatsApp support code",
                "ordering": ("-created_at",),
            },
        ),
    ]
