# Generated by Django 5.1.15 on 2026-07-17 15:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("student_id", models.CharField(max_length=32, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="students/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("home_address", models.TextField(blank=True)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                ("guardian_relation", models.CharField(blank=True, max_length=50)),
                ("guardian_phone", models.CharField(blank=True, max_length=32)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("grade", models.CharField(blank=True, max_length=50)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="schools.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ("first_name", "last_name"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="students_st_search__87debe_gin"
                    )
                ],
            },
        ),
    ]
