# Generated by Django 5.1.15 on 2026-07-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_enrollment_date_student_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="student",
            name="program",
        ),
    ]
