# Generated by Django 5.1.15 on 2026-07-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_nationality_remove_student_program"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="transport_pickup",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="transport.transportroute",
            ),
        ),
    ]
