# Generated by Django 5.1.15 on 2026-07-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0001_initial"),
        ("students", "0004_student_transport_pickup_student_transport_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hostel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="hostel.hostel",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_room",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
