# Generated by Django 5.1.15 on 2026-07-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_parent_student_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent",
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
    ]
