# Generated by Django 5.1.15 on 2026-07-21 12:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "monthly_fare",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registration_number", models.CharField(max_length=32, unique=True)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("driver_name", models.CharField(blank=True, max_length=120)),
                ("driver_phone", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="transport.transportroute",
                    ),
                ),
            ],
            options={
                "ordering": ("registration_number",),
            },
        ),
        migrations.CreateModel(
            name="TransportExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("driver_salary", "Driver Salary"),
                            ("maintenance", "Maintenance"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        default="fuel",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("spent_on", models.DateField(db_index=True)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("payment_method", models.CharField(blank=True, max_length=32)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="transport.transportroute",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ("-spent_on", "-created_at"),
            },
        ),
    ]
