"""
Platform-console admin (public schema). Everything registers on `platform_admin`
(superuser-only). Tenant business models are deliberately NOT registered — their
tables don't exist in the public schema, so browsing them here would 500. Schools
use the app UI; this console manages the registry, provisioning, and backups.
"""

from __future__ import annotations

from datetime import timedelta

from django import forms
from django.contrib import messages
from django.contrib.admin import ModelAdmin, TabularInline, action, display
from django.contrib.admin.models import LogEntry
from django.contrib.auth.admin import UserAdmin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.utils.html import format_html
from django_tenants.utils import get_public_schema_name, tenant_context

from apps.accounts.models import User

from .admin_site import platform_admin
from .models import BackupRun, Client, Domain, Plan
from .services import provision_school

_STAT_TTL = 300  # cross-tenant stat columns are cached to avoid an N+1 across schemas


def _public() -> str:
    return get_public_schema_name()


def _tenant_stat(client: Client, key: str, fn):
    """Cached per-schema stat (keyed by schema) so the changelist isn't an N+1."""
    if client.schema_name == _public():
        return "—"
    cache_key = f"admin_stat:{client.schema_name}:{key}"
    val = cache.get(cache_key)
    if val is None:
        try:
            with tenant_context(client):
                val = fn()
        except Exception:
            return "?"
        cache.set(cache_key, val, _STAT_TTL)
    return val


# --------------------------------------------------------------------------- #
# Domains — inline on Client (manage hostnames in one place) + standalone.
# --------------------------------------------------------------------------- #
class DomainInline(TabularInline):
    model = Domain
    extra = 0
    fields = ("domain", "is_primary")


# --------------------------------------------------------------------------- #
# Provision-a-school form (used only on the Add page).
# --------------------------------------------------------------------------- #
class ProvisionSchoolForm(forms.ModelForm):
    admin_full_name = forms.CharField(label="First admin — full name")
    admin_email = forms.EmailField(label="First admin — email")
    admin_password = forms.CharField(
        label="First admin — password", widget=forms.PasswordInput, min_length=8
    )

    class Meta:
        model = Client
        fields = ("name", "slug")  # schema/code are auto-generated by provision_school

    def clean_slug(self):
        return (self.cleaned_data.get("slug") or "").strip() or None


# --------------------------------------------------------------------------- #
# Lifecycle actions.
# --------------------------------------------------------------------------- #
@action(description="Resend verification email to school admin(s)")
def resend_admin_verification(modeladmin, request, queryset):
    from apps.accounts.services import send_verification_email

    total = 0
    for client in queryset.exclude(schema_name=_public()):
        with tenant_context(client):
            for user in User.objects.filter(email_verified=False):
                send_verification_email(user, school_name=client.name, slug=client.slug)
                total += 1
    modeladmin.message_user(request, f"Queued {total} verification email(s).", messages.SUCCESS)


def _require_reauth(modeladmin, request) -> bool:
    """Block a sensitive action unless the operator re-authenticated recently."""
    from apps.core.middleware import reauth_fresh

    if reauth_fresh(request):
        return True
    modeladmin.message_user(
        request,
        "This action needs a fresh login. Log out and back in, then retry.",
        messages.ERROR,
    )
    return False


@action(description="Suspend (block sign-in)")
def suspend_schools(modeladmin, request, queryset):
    if not _require_reauth(modeladmin, request):
        return
    n = queryset.exclude(schema_name=_public()).update(is_active=False)
    modeladmin.message_user(request, f"Suspended {n} school(s).", messages.WARNING)


@action(description="Reactivate")
def reactivate_schools(modeladmin, request, queryset):
    n = queryset.update(is_active=True)
    modeladmin.message_user(request, f"Reactivated {n} school(s).", messages.SUCCESS)


@action(description="Extend trial by 30 days")
def extend_trial(modeladmin, request, queryset):
    new_until = timezone.now().date() + timedelta(days=30)
    n = queryset.update(on_trial=True, paid_until=new_until)
    modeladmin.message_user(request, f"Extended trial for {n} school(s) to {new_until}.")


@action(description="Mark as paid (1 year)")
def mark_paid(modeladmin, request, queryset):
    paid_until = timezone.now().date() + timedelta(days=365)
    n = queryset.update(on_trial=False, paid_until=paid_until)
    modeladmin.message_user(request, f"Marked {n} school(s) paid until {paid_until}.")


@action(description="Impersonate a school admin (support)")
def impersonate_admin(modeladmin, request, queryset):
    from .impersonation import impersonation_url, make_ticket

    if not _require_reauth(modeladmin, request):
        return
    clients = list(queryset.exclude(schema_name=_public()))
    if len(clients) != 1:
        modeladmin.message_user(
            request, "Select exactly one school to impersonate.", messages.ERROR
        )
        return
    client = clients[0]
    with tenant_context(client):
        target = (
            User.objects.filter(role="admin", is_active=True).first()
            or User.objects.filter(is_active=True).first()
        )
    if target is None or not client.slug:
        modeladmin.message_user(
            request, "No active admin user / subdomain for this school.", messages.ERROR
        )
        return
    ticket = make_ticket(operator=request.user, target_user_id=target.pk, schema=client.schema_name)
    from apps.core.audit import record_audit

    with tenant_context(client):
        record_audit(
            action="impersonation.issued",
            entity=None,
            summary=f"{request.user.email} issued impersonation for {target.email}",
            actor=None,
        )
    return HttpResponseRedirect(impersonation_url(slug=client.slug, ticket=ticket))


@action(description="Export all data (JSON)")
def export_tenant_action(modeladmin, request, queryset):
    from .offboarding import export_tenant_json

    clients = list(queryset.exclude(schema_name=_public()))
    if len(clients) != 1:
        modeladmin.message_user(request, "Select exactly one school to export.", messages.ERROR)
        return
    client = clients[0]
    payload = export_tenant_json(client)
    resp = HttpResponse(payload, content_type="application/json")
    resp["Content-Disposition"] = f'attachment; filename="{client.schema_name}-export.json"'
    return resp


@action(description="Archive (suspend + mark for deletion)")
def archive_action(modeladmin, request, queryset):
    from .offboarding import archive_tenant

    n = 0
    for client in queryset.exclude(schema_name=_public()):
        archive_tenant(client, actor=request.user)
        n += 1
    modeladmin.message_user(request, f"Archived {n} school(s).", messages.WARNING)


@action(description="⚠ Permanently DELETE archived schools (drops schema)")
def delete_archived_action(modeladmin, request, queryset):
    from apps.core.services import ServiceError

    from .offboarding import delete_tenant

    if not _require_reauth(modeladmin, request):
        return
    deleted, skipped = 0, 0
    for client in queryset.exclude(schema_name=_public()):
        try:
            delete_tenant(client, actor=request.user)
            deleted += 1
        except ServiceError:
            skipped += 1
    modeladmin.message_user(
        request,
        f"Deleted {deleted} archived school(s); skipped {skipped} (not archived).",
        messages.ERROR if deleted else messages.WARNING,
    )


class ClientAdmin(ModelAdmin):
    list_display = (
        "name",
        "code",
        "status_badge",
        "plan",
        "students",
        "users",
        "unverified_staff",
        "last_activity",
        "open_links",
        "created_on",
    )
    list_filter = ("is_active", "is_archived", "on_trial", "plan")
    list_select_related = ("plan",)
    autocomplete_fields = ("plan",)
    search_fields = ("name", "schema_name", "code", "slug")
    date_hierarchy = "created_on"
    ordering = ("-created_on",)
    inlines = [DomainInline]
    actions = [
        resend_admin_verification,
        suspend_schools,
        reactivate_schools,
        extend_trial,
        mark_paid,
        impersonate_admin,
        export_tenant_action,
        archive_action,
        delete_archived_action,
    ]
    readonly_fields = ("schema_name", "code", "created_on", "open_links")
    fieldsets = (
        ("School", {"fields": ("name", "slug", "code", "schema_name", "open_links")}),
        ("Billing", {"fields": ("plan", "on_trial", "paid_until", "is_active", "is_archived")}),
        ("Provisioning", {"fields": ("created_on",)}),
    )

    # --- provisioning: the Add page provisions a real school (schema + domain +
    #     verified-admin email), not a bare Client row. ---
    def get_form(self, request, obj=None, **kwargs):
        if obj is None:
            kwargs["form"] = ProvisionSchoolForm
        return super().get_form(request, obj, **kwargs)

    def get_inline_instances(self, request, obj=None):
        # No domain inline on the Add page — provision_school creates the domain.
        return [] if obj is None else super().get_inline_instances(request, obj)

    def save_model(self, request, obj, form, change):
        if change:
            obj.save()
            return
        if not _require_reauth(self, request):
            raise PermissionDenied("Re-authentication required to provision a school.")
        d = form.cleaned_data
        client = provision_school(
            name=d["name"],
            slug=d.get("slug"),
            admin_full_name=d["admin_full_name"],
            admin_email=d["admin_email"],
            admin_password=d["admin_password"],
        )
        # Rebind the admin's in-memory object to the created row so the post-save
        # redirect + log entry point at the real school (do NOT re-save).
        obj.pk = client.pk
        obj.schema_name = client.schema_name
        obj.name = client.name
        obj.slug = client.slug
        obj.code = client.code
        self.message_user(
            request,
            f"Provisioned {client.name} ({client.code}) at {client.slug}. "
            "A verification email was sent to the admin.",
            messages.SUCCESS,
        )

    def has_delete_permission(self, request, obj=None):
        # Never let a school's schema be nuked from the admin (auto_drop_schema
        # is off too — belt & braces).
        return False

    # --- display columns ---
    @display(description="Status")
    def status_badge(self, obj):
        if obj.schema_name == _public():
            return format_html("<b>platform</b>")
        if not obj.is_active:
            return format_html('<span style="color:#b91c1c;font-weight:600">● suspended</span>')
        plan = "trial" if obj.on_trial else "paid"
        color = "#d97706" if obj.on_trial else "#059669"
        return format_html(
            '<span style="color:{};font-weight:600">● active · {}</span>', color, plan
        )

    @display(description="Students")
    def students(self, obj):
        from apps.students.models import Student

        return _tenant_stat(obj, "students", lambda: Student.objects.alive().count())

    @display(description="Users")
    def users(self, obj):
        return _tenant_stat(obj, "users", lambda: User.objects.count())

    @display(description="Unverified staff")
    def unverified_staff(self, obj):
        return _tenant_stat(
            obj, "unverified", lambda: User.objects.filter(email_verified=False).count()
        )

    @display(description="Last activity")
    def last_activity(self, obj):
        def _last():
            from apps.core.models import AuditLog

            row = (
                AuditLog.objects.order_by("-created_at")
                .values_list("created_at", flat=True)
                .first()
            )
            return row.strftime("%Y-%m-%d %H:%M") if row else "—"

        return _tenant_stat(obj, "last_activity", _last)

    @display(description="Open")
    def open_links(self, obj):
        if not obj.slug:
            return "—"
        from django.conf import settings

        base = getattr(settings, "TENANT_BASE_DOMAIN", "localhost")
        scheme = getattr(settings, "FRONTEND_SCHEME", "http")
        port = getattr(settings, "FRONTEND_PORT", "5173")
        app_url = f"{scheme}://{obj.slug}.{base}:{port}/"
        return format_html('<a href="{}" target="_blank" rel="noopener">app ↗</a>', app_url)


class DomainAdmin(ModelAdmin):
    list_display = ("domain", "tenant", "is_primary")
    search_fields = ("domain",)
    list_select_related = ("tenant",)
    autocomplete_fields = ("tenant",)


class BackupRunAdmin(ModelAdmin):
    """Read-only view of verified backups (CLAUDE.md §10)."""

    list_display = (
        "label",
        "status",
        "verified",
        "size_bytes",
        "table_count_total",
        "created_at",
    )
    list_filter = ("status", "verified")
    date_hierarchy = "created_at"
    readonly_fields = tuple(f.name for f in BackupRun._meta.fields)

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


class ActivityLogAdmin(ModelAdmin):
    """Read-only 'who changed what' in the admin (auditors ask for this)."""

    list_display = ("action_time", "user", "content_type", "object_repr", "action_flag")
    list_filter = ("action_flag", "content_type")
    search_fields = ("object_repr", "change_message")
    date_hierarchy = "action_time"
    list_select_related = ("user", "content_type")

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


class PlatformUserAdmin(UserAdmin):
    """Platform (public-schema) users. Tenant staff live in each school's schema."""

    list_display = ("username", "email", "role", "is_superuser", "is_active", "email_verified")
    list_filter = ("role", "is_superuser", "is_active", "email_verified")
    fieldsets = UserAdmin.fieldsets + (("SFMS", {"fields": ("role", "phone", "email_verified")}),)


class PlanAdmin(ModelAdmin):
    list_display = ("name", "price_monthly", "currency", "max_students", "is_active")
    search_fields = ("name",)


platform_admin.register(Plan, PlanAdmin)
platform_admin.register(Client, ClientAdmin)
platform_admin.register(Domain, DomainAdmin)
platform_admin.register(BackupRun, BackupRunAdmin)
platform_admin.register(LogEntry, ActivityLogAdmin)
platform_admin.register(User, PlatformUserAdmin)
