"""
Platform-console admin (public schema). Everything registers on `platform_admin`
(superuser-only). Tenant business models are deliberately NOT registered — their
tables don't exist in the public schema, so browsing them here would 500. Schools
use the app UI; this console manages the registry, provisioning, and backups.
"""

from __future__ import annotations

from datetime import timedelta

from django import forms
from django.contrib import messages
from django.contrib.admin import action, display
from django.contrib.admin.models import LogEntry
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import path, reverse
from django.utils import timezone
from django.utils.html import format_html
from django_tenants.utils import get_public_schema_name, tenant_context
from unfold.admin import ModelAdmin, TabularInline
from unfold.forms import AdminPasswordChangeForm, UserChangeForm, UserCreationForm

from apps.accounts.models import User

from .admin_site import platform_admin
from .models import BackupRun, Client, Domain, Plan, WhatsAppSupportCode
from .services import provision_school

_STAT_TTL = 300  # cross-tenant stat columns are cached to avoid an N+1 across schemas


def _public() -> str:
    return get_public_schema_name()


def _tenant_stat(client: Client, key: str, fn):
    """Cached per-schema stat (keyed by schema) so the changelist isn't an N+1."""
    if client.schema_name == _public():
        return "—"
    cache_key = f"admin_stat:{client.schema_name}:{key}"
    val = cache.get(cache_key)
    if val is None:
        try:
            with tenant_context(client):
                val = fn()
        except Exception:
            return "?"
        cache.set(cache_key, val, _STAT_TTL)
    return val


# --------------------------------------------------------------------------- #
# Domains — inline on Client (manage hostnames in one place) + standalone.
# --------------------------------------------------------------------------- #
class DomainInline(TabularInline):
    model = Domain
    extra = 0
    fields = ("domain", "is_primary")


# --------------------------------------------------------------------------- #
# Provision-a-school form (used only on the Add page).
# --------------------------------------------------------------------------- #
class ProvisionSchoolForm(forms.ModelForm):
    admin_full_name = forms.CharField(label="First admin — full name")
    admin_email = forms.EmailField(label="First admin — email")
    admin_password = forms.CharField(
        label="First admin — password", widget=forms.PasswordInput, min_length=8
    )

    class Meta:
        model = Client
        fields = ("name", "slug")  # schema/code are auto-generated by provision_school

    def clean_slug(self):
        return (self.cleaned_data.get("slug") or "").strip() or None


# --------------------------------------------------------------------------- #
# Lifecycle actions.
# --------------------------------------------------------------------------- #
@action(description="Resend verification email to school admin(s)")
def resend_admin_verification(modeladmin, request, queryset):
    from apps.accounts.services import send_verification_email

    total = 0
    for client in queryset.exclude(schema_name=_public()):
        with tenant_context(client):
            for user in User.objects.filter(email_verified=False):
                send_verification_email(user, school_name=client.name, slug=client.slug)
                total += 1
    modeladmin.message_user(request, f"Queued {total} verification email(s).", messages.SUCCESS)


def _require_reauth(modeladmin, request) -> bool:
    """Block a sensitive action unless the operator re-authenticated recently."""
    from apps.core.middleware import reauth_fresh

    if reauth_fresh(request):
        return True
    modeladmin.message_user(
        request,
        "This action needs a fresh login. Log out and back in, then retry.",
        messages.ERROR,
    )
    return False


@action(description="Suspend (block sign-in)")
def suspend_schools(modeladmin, request, queryset):
    if not _require_reauth(modeladmin, request):
        return
    n = queryset.exclude(schema_name=_public()).update(is_active=False)
    modeladmin.message_user(request, f"Suspended {n} school(s).", messages.WARNING)


@action(description="Reactivate")
def reactivate_schools(modeladmin, request, queryset):
    n = queryset.update(is_active=True)
    modeladmin.message_user(request, f"Reactivated {n} school(s).", messages.SUCCESS)


@action(description="Extend trial by 30 days")
def extend_trial(modeladmin, request, queryset):
    new_until = timezone.now().date() + timedelta(days=30)
    n = queryset.update(on_trial=True, paid_until=new_until)
    modeladmin.message_user(request, f"Extended trial for {n} school(s) to {new_until}.")


@action(description="Mark as paid (1 year)")
def mark_paid(modeladmin, request, queryset):
    paid_until = timezone.now().date() + timedelta(days=365)
    n = queryset.update(on_trial=False, paid_until=paid_until)
    modeladmin.message_user(request, f"Marked {n} school(s) paid until {paid_until}.")


@action(description="Impersonate a school admin (support)")
def impersonate_admin(modeladmin, request, queryset):
    from .impersonation import impersonation_url, make_ticket

    if not _require_reauth(modeladmin, request):
        return
    clients = list(queryset.exclude(schema_name=_public()))
    if len(clients) != 1:
        modeladmin.message_user(
            request, "Select exactly one school to impersonate.", messages.ERROR
        )
        return
    client = clients[0]
    with tenant_context(client):
        target = (
            User.objects.filter(role="admin", is_active=True).first()
            or User.objects.filter(is_active=True).first()
        )
    if target is None or not client.slug:
        modeladmin.message_user(
            request, "No active admin user / subdomain for this school.", messages.ERROR
        )
        return
    ticket = make_ticket(operator=request.user, target_user_id=target.pk, schema=client.schema_name)
    from apps.core.audit import record_audit

    with tenant_context(client):
        record_audit(
            action="impersonation.issued",
            entity=None,
            summary=f"{request.user.email} issued impersonation for {target.email}",
            actor=None,
        )
    return HttpResponseRedirect(impersonation_url(slug=client.slug, ticket=ticket))


@action(description="Export all data (JSON)")
def export_tenant_action(modeladmin, request, queryset):
    from .offboarding import export_tenant_json

    clients = list(queryset.exclude(schema_name=_public()))
    if len(clients) != 1:
        modeladmin.message_user(request, "Select exactly one school to export.", messages.ERROR)
        return
    client = clients[0]
    payload = export_tenant_json(client)
    resp = HttpResponse(payload, content_type="application/json")
    resp["Content-Disposition"] = f'attachment; filename="{client.schema_name}-export.json"'
    return resp


@action(description="Archive (suspend + mark for deletion)")
def archive_action(modeladmin, request, queryset):
    from .offboarding import archive_tenant

    n = 0
    for client in queryset.exclude(schema_name=_public()):
        archive_tenant(client, actor=request.user)
        n += 1
    modeladmin.message_user(request, f"Archived {n} school(s).", messages.WARNING)


@action(description="⚠ Permanently DELETE archived schools (drops schema)")
def delete_archived_action(modeladmin, request, queryset):
    from apps.core.services import ServiceError

    from .offboarding import delete_tenant

    if not _require_reauth(modeladmin, request):
        return
    deleted, skipped = 0, 0
    for client in queryset.exclude(schema_name=_public()):
        try:
            delete_tenant(client, actor=request.user)
            deleted += 1
        except ServiceError:
            skipped += 1
    modeladmin.message_user(
        request,
        f"Deleted {deleted} archived school(s); skipped {skipped} (not archived).",
        messages.ERROR if deleted else messages.WARNING,
    )


@action(description="Back up now (per-school)")
def backup_now_action(modeladmin, request, queryset):
    from .tasks import backup_school

    n = 0
    for client in queryset.exclude(schema_name=_public()):
        backup_school.delay(client.schema_name)
        n += 1
    modeladmin.message_user(
        request,
        f"Queued a backup for {n} school(s). They'll appear under Backup runs shortly.",
        messages.SUCCESS,
    )


class ClientAdmin(ModelAdmin):
    list_display = (
        "name",
        "code",
        "status_badge",
        "plan",
        "students",
        "users",
        "unverified_staff",
        "last_activity",
        "open_links",
        "created_on",
    )
    list_filter = ("is_active", "is_archived", "on_trial", "plan")
    list_select_related = ("plan",)
    autocomplete_fields = ("plan",)
    search_fields = ("name", "schema_name", "code", "slug")
    date_hierarchy = "created_on"
    ordering = ("-created_on",)
    inlines = [DomainInline]
    actions = [
        resend_admin_verification,
        suspend_schools,
        reactivate_schools,
        extend_trial,
        mark_paid,
        impersonate_admin,
        export_tenant_action,
        backup_now_action,
        archive_action,
        delete_archived_action,
    ]
    readonly_fields = ("schema_name", "code", "created_on", "open_links")
    fieldsets = (
        ("School", {"fields": ("name", "slug", "code", "schema_name", "open_links")}),
        ("Billing", {"fields": ("plan", "on_trial", "paid_until", "is_active", "is_archived")}),
        ("Provisioning", {"fields": ("created_on",)}),
    )

    # --- provisioning: the Add page provisions a real school (schema + domain +
    #     verified-admin email), not a bare Client row. ---
    def get_form(self, request, obj=None, **kwargs):
        if obj is None:
            kwargs["form"] = ProvisionSchoolForm
        return super().get_form(request, obj, **kwargs)

    def get_inline_instances(self, request, obj=None):
        # No domain inline on the Add page — provision_school creates the domain.
        return [] if obj is None else super().get_inline_instances(request, obj)

    def save_model(self, request, obj, form, change):
        if change:
            obj.save()
            return
        if not _require_reauth(self, request):
            raise PermissionDenied("Re-authentication required to provision a school.")
        d = form.cleaned_data
        client = provision_school(
            name=d["name"],
            slug=d.get("slug"),
            admin_full_name=d["admin_full_name"],
            admin_email=d["admin_email"],
            admin_password=d["admin_password"],
        )
        # Rebind the admin's in-memory object to the created row so the post-save
        # redirect + log entry point at the real school (do NOT re-save).
        obj.pk = client.pk
        obj.schema_name = client.schema_name
        obj.name = client.name
        obj.slug = client.slug
        obj.code = client.code
        self.message_user(
            request,
            f"Provisioned {client.name} ({client.code}) at {client.slug}. "
            "A verification email was sent to the admin.",
            messages.SUCCESS,
        )

    def has_delete_permission(self, request, obj=None):
        # Never let a school's schema be nuked from the admin (auto_drop_schema
        # is off too — belt & braces).
        return False

    # --- display columns ---
    @display(description="Status")
    def status_badge(self, obj):
        if obj.schema_name == _public():
            return format_html("<b>platform</b>")
        if not obj.is_active:
            return format_html('<span style="color:#b91c1c;font-weight:600">● suspended</span>')
        plan = "trial" if obj.on_trial else "paid"
        color = "#d97706" if obj.on_trial else "#059669"
        return format_html(
            '<span style="color:{};font-weight:600">● active · {}</span>', color, plan
        )

    @display(description="Students")
    def students(self, obj):
        from apps.students.models import Student

        return _tenant_stat(obj, "students", lambda: Student.objects.alive().count())

    @display(description="Users")
    def users(self, obj):
        return _tenant_stat(obj, "users", lambda: User.objects.count())

    @display(description="Unverified staff")
    def unverified_staff(self, obj):
        return _tenant_stat(
            obj, "unverified", lambda: User.objects.filter(email_verified=False).count()
        )

    @display(description="Last activity")
    def last_activity(self, obj):
        def _last():
            from apps.core.models import AuditLog

            row = (
                AuditLog.objects.order_by("-created_at")
                .values_list("created_at", flat=True)
                .first()
            )
            return row.strftime("%Y-%m-%d %H:%M") if row else "—"

        return _tenant_stat(obj, "last_activity", _last)

    @display(description="Open")
    def open_links(self, obj):
        if not obj.slug:
            return "—"
        from django.conf import settings

        base = getattr(settings, "TENANT_BASE_DOMAIN", "localhost")
        scheme = getattr(settings, "FRONTEND_SCHEME", "http")
        port = getattr(settings, "FRONTEND_PORT", "5173")
        app_url = f"{scheme}://{obj.slug}.{base}:{port}/"
        return format_html('<a href="{}" target="_blank" rel="noopener">app ↗</a>', app_url)


class DomainAdmin(ModelAdmin):
    list_display = ("domain", "tenant", "is_primary")
    search_fields = ("domain",)
    list_select_related = ("tenant",)
    autocomplete_fields = ("tenant",)


@action(description="Verify integrity + restore-drill")
def verify_backup_action(modeladmin, request, queryset):
    from .backups import verify_backup

    n = 0
    for run in queryset:
        verify_backup(run, actor=request.user)
        n += 1
    modeladmin.message_user(request, f"Verified {n} backup(s).", messages.SUCCESS)


@action(description="⚠ RESTORE selected backup into its school (destructive)")
def restore_backup_action(modeladmin, request, queryset):
    from apps.core.services import ServiceError

    from .backups import restore_schema_backup

    if not _require_reauth(modeladmin, request):
        return
    runs = [r for r in queryset if r.schema_name]
    if len(runs) != 1:
        modeladmin.message_user(
            request, "Select exactly one per-school backup to restore.", messages.ERROR
        )
        return
    run = runs[0]
    try:
        restore_schema_backup(run, actor=request.user)
    except ServiceError as exc:
        modeladmin.message_user(request, f"Restore failed: {exc}", messages.ERROR)
        return
    modeladmin.message_user(
        request,
        f"Restored '{run.schema_name}' from backup '{run.label}'. Verify the school before use.",
        messages.WARNING,
    )


class BackupRunAdmin(ModelAdmin):
    """Backups: view, download and restore per-school dumps (CLAUDE.md §10)."""

    list_display = (
        "label",
        "school",
        "status",
        "verified",
        "size_display",
        "table_count_total",
        "download_link",
        "created_at",
    )
    list_filter = ("status", "verified", "client")
    search_fields = ("label", "schema_name", "client__name")
    date_hierarchy = "created_at"
    readonly_fields = tuple(f.name for f in BackupRun._meta.fields)
    actions = [verify_backup_action, restore_backup_action]

    @display(description="School")
    def school(self, obj):
        return obj.client.name if obj.client else (obj.schema_name or "— (whole cluster)")

    @display(description="Size")
    def size_display(self, obj):
        mb = (obj.size_bytes or 0) / (1024 * 1024)
        return f"{mb:.1f} MB"

    @display(description="File")
    def download_link(self, obj):
        if obj.storage_key or obj.path:
            url = reverse("platform_admin:tenants_backuprun_download", args=[obj.pk])
            return format_html('<a href="{}">⬇ Download</a>', url)
        return "—"

    def get_urls(self):
        urls = super().get_urls()
        custom = [
            path(
                "<int:pk>/download/",
                self.admin_site.admin_view(self.download_view),
                name="tenants_backuprun_download",
            )
        ]
        return custom + urls

    def download_view(self, request, pk):
        from django.http import FileResponse, Http404

        from .backups import materialize

        run = BackupRun.objects.filter(pk=pk).first()
        if run is None or not (run.storage_key or run.path):
            raise Http404("Backup file not found.")
        local = materialize(run)
        resp = FileResponse(open(local, "rb"), as_attachment=True, filename=f"{run.label}.dump")
        return resp

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        # Read-only fields, but allow the detail view + actions.
        return True

    def has_delete_permission(self, request, obj=None):
        return True  # prune old backups


class ActivityLogAdmin(ModelAdmin):
    """Read-only 'who changed what' in the admin (auditors ask for this)."""

    list_display = ("action_time", "user", "content_type", "object_repr", "action_flag")
    list_filter = ("action_flag", "content_type")
    search_fields = ("object_repr", "change_message")
    date_hierarchy = "action_time"
    list_select_related = ("user", "content_type")

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


class PlatformUserAdmin(BaseUserAdmin, ModelAdmin):
    """Platform (public-schema) users. Tenant staff live in each school's schema."""

    # Unfold-styled auth forms (password widgets render correctly).
    form = UserChangeForm
    add_form = UserCreationForm
    change_password_form = AdminPasswordChangeForm

    list_display = ("username", "email", "role", "is_superuser", "is_active", "email_verified")
    list_filter = ("role", "is_superuser", "is_active", "email_verified")
    fieldsets = BaseUserAdmin.fieldsets + (
        ("SFMS", {"fields": ("role", "phone", "email_verified")}),
    )


class PlanAdmin(ModelAdmin):
    list_display = ("name", "price_monthly", "currency", "max_students", "is_active")
    search_fields = ("name",)


class WhatsAppSupportCodeAdmin(ModelAdmin):
    """Verify a WhatsApp support code: search the code the customer sent."""

    list_display = (
        "code",
        "verified_badge",
        "school_name",
        "user_name",
        "created_at",
        "expires_at",
    )
    list_filter = ("status",)
    search_fields = ("code", "school_name", "school_code", "user_email", "user_phone")
    # Everything is read-only except `status`, which the agent flips to verified/closed.
    readonly_fields = tuple(f.name for f in WhatsAppSupportCode._meta.fields if f.name != "status")
    ordering = ("-created_at",)

    @display(description="Valid")
    def verified_badge(self, obj):
        if obj.is_expired and obj.status == WhatsAppSupportCode.Status.ISSUED:
            return format_html('<span style="color:#b45309">expired</span>')
        colors = {"issued": "#2563eb", "verified": "#059669", "closed": "#64748b"}
        return format_html(
            '<b style="color:{}">{}</b>',
            colors.get(obj.status, "#64748b"),
            obj.get_status_display(),
        )

    def has_add_permission(self, request):
        return False  # codes are minted by the app, never by hand

    def has_change_permission(self, request, obj=None):
        return True  # allow marking verified/closed


platform_admin.register(Plan, PlanAdmin)
platform_admin.register(Client, ClientAdmin)
platform_admin.register(Domain, DomainAdmin)
platform_admin.register(BackupRun, BackupRunAdmin)
platform_admin.register(WhatsAppSupportCode, WhatsAppSupportCodeAdmin)
platform_admin.register(LogEntry, ActivityLogAdmin)
platform_admin.register(User, PlatformUserAdmin)
