# Generated by Django 5.1.15 on 2026-07-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_discountrule_studentdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="feetype",
            name="hsn_sac",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
